//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoNewsEntities : DbContext
    {
        public AutoNewsEntities()
            : base("name=AutoNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Crawler> Crawlers { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<Market> Markets { get; set; }
        public DbSet<MarketType> MarketTypes { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<Log> Logs { get; set; }
    }
}
