//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<int> MarketId { get; set; }
        public bool Published { get; set; }
    
        public virtual Market Market { get; set; }
    }
}
