//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Crawlers = new HashSet<Crawler>();
            this.News = new HashSet<News>();
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public int MarketTypeId { get; set; }
        public string Name { get; set; }
        public int MarketCrmId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public bool RunOnHoliday { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public bool Auto { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual ICollection<Crawler> Crawlers { get; set; }
        public virtual MarketType MarketType { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
