//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Prices = new HashSet<Price>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int MarketId { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual ICollection<Price> Prices { get; set; }
        public virtual Market Market { get; set; }
    }
}
